### ISSUE TITLE
undefined local variable or method `node'

### ISSUE THREAD

**Issue by martinthegeek** [chef-cookbooks/partial_search#5]
I am trying to use the ssh_known_hosts recipe on a new install and getting this error:

```
[root@centos6-test3 mandrews]# chef-client
Starting Chef Client, version 11.6.0 
resolving cookbooks for run list: ["ssh_known_hosts"]
Synchronizing Cookbooks:
  - partial_search
  - ssh_known_hosts
Compiling Cookbooks...

================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/ssh_known_hosts/recipes/default.rb
================================================================================


NameError
---------
undefined local variable or method `node' for #<Chef::PartialSearch:0x000000027a5970>


Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/partial_search/libraries/partial_search.rb:37:in `initialize'
  /var/chef/cache/cookbooks/partial_search/libraries/partial_search.rb:159:in `new'
  /var/chef/cache/cookbooks/partial_search/libraries/partial_search.rb:159:in `partial_search'
  /var/chef/cache/cookbooks/ssh_known_hosts/recipes/default.rb:31:in `from_file'


Relevant File Content:
----------------------
/var/chef/cache/cookbooks/partial_search/libraries/partial_search.rb:

 30:  class Chef
 31:    class PartialSearch
 32:
 33:      attr_accessor :rest
 34:
 35:      def initialize(url=nil)
 36:        @rest = ::Chef::REST.new(url || ::Chef::Config[:chef_server_url])
 37>>       @cache = node.run_state["chef_partial_search_cache"] ||= {}
 38:      end
 39:
 40:      # Search Solr for objects of a given type, for a given query. If you give
 41:      # it a block, it will handle the paging for you dynamically.
 42:      def search(type, query='*:*', args={}, &block)
 43:        raise ArgumentError, "Type must be a string or a symbol!" unless (type.kind_of?(String) || type.kind_of?(Symbol))
 44:
 45:        sort = args.include?(:sort) ? args[:sort] : 'X_CHEF_id_CHEF_X asc'
 46:        start = args.include?(:start) ? args[:start] : 0



[2013-10-09T13:59:42-04:00] ERROR: Running exception handlers
[2013-10-09T13:59:42-04:00] ERROR: Exception handlers complete
[2013-10-09T13:59:42-04:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated
[2013-10-09T13:59:42-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

I am using chef server 11.0.8 and chef client 11.6.0 running on Centos 6.4

**Comment by tas50** [comment]
We've deprecated this cookbook as this functionality is now built into chef client.  If you're still having the same issue please report it against the chef/chef repository.
